package main;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Scanner;

import dao.CustomerDAO;
import dao.ServiceDAO;
import dao.VehicleDAO;
import model.Customer;
import model.Vehicle;
import model.Service;

public class VehicleServiceApp {

	public static void main(String[] args) throws SQLException {
	
		Scanner sc = new Scanner(System.in);
		CustomerDAO cdao = new CustomerDAO();
		VehicleDAO vdao = new VehicleDAO();
		ServiceDAO sdao = new ServiceDAO();
		
		while(true)
		{
			System.out.println("===== VEHICLE SERVICE MANAGEMENT SYSTEM =====");
			System.out.println("1. Customer");
			System.out.println("2. Vehicle");
			System.out.println("3. Service");
			System.out.println("0. Exit");
			System.out.print("Enter your choice : ");
			
			int mainChoice = sc.nextInt();
			sc.nextLine();
			
			switch(mainChoice)
			{
				case 1:
					customerMenu(sc, cdao);
					break;
				case 2:
					vehicleMenu(sc, vdao);
					break;
				case 3:
					serviceMenu(sc, sdao);
					break;
				case 0:
                    System.out.println("Exiting program...");
                    sc.close();
                    return;
                default:
                    System.out.println("Invalid choice! Please try again.");
			}
		}
	}

	  // ---------------- CUSTOMER MENU ----------------
	private static void customerMenu(Scanner sc, CustomerDAO cdao) throws SQLException
	{
		while(true)
		{
			 System.out.println("\n--- CUSTOMER MENU ---");
	            System.out.println("1. Add Customer");
	            System.out.println("2. View Customers");
	            System.out.println("3. Update Customer");
	            System.out.println("4. Specific update Customer");
	            System.out.println("5. Delete Customer");
	            System.out.println("0. Back to Main Menu");
	            System.out.print("Enter your choice: ");

	            int choice = sc.nextInt();
	            sc.nextLine();
	            
	            switch(choice)
	            {
	            	case 1:
						System.out.print("Enter Name :");
						String name = sc.nextLine();
						System.out.print("Enter Phone Number :");
						String phoneno = sc.nextLine();
						System.out.print("Enter EmailID :");
						String emailid = sc.nextLine();
						
						// ID will be auto-generated by the database
						Customer c = new Customer(0, name, phoneno, emailid);
		                boolean added = cdao.addCustomer(c);

		                if (added)
		                    System.out.println("Customer added successfully!");
		                else
		                    System.out.println("Failed to add customer!");
		                break;
		                
	            	case 2:
	            		ArrayList<Customer> allCustomer = cdao.viewCustomers();
						
						for(Customer k : allCustomer)
						{
							System.out.println(k.getcID() + "  " + k.getcName() + "  " + k.getPhoneNo() + "  " + k.getEmailID());
						}
						break;
						
	            	case 3:
	            		System.out.print("Enter ID :");
                        int cid = sc.nextInt();
                        System.out.print("Enter new Name :");
                        String cname = sc.next();
                        System.out.print("Enter Phone Number :");
                        String cphoneno = sc.next();
                        System.out.print("Enter EmailID :");
                        String cemailid = sc.next();
                        
                        Customer u = new Customer(cid, cname, cphoneno, cemailid);
                        boolean updated = cdao.editCustomer(u);
                        
                        if (updated)
                            System.out.println("Customer updated successfully!");
                        else
                            System.out.println("Failed to update customer!");
                        break;
                       
	            	case 4:
	            		try {
	            	        System.out.println("Which field do you want to update?");
	            	        System.out.println("1. Name\n2. Phone No\n3. Email ID");
	            	        int ch = sc.nextInt();

	            	        System.out.print("Enter Customer ID :");
	            	        int uid = sc.nextInt();
	            	        sc.nextLine(); 

	            	        String newValue = "";
 
	            	        switch (ch) {
	            	            case 1:
	            	                System.out.print("Enter new Name :");
	            	                newValue = sc.nextLine();
	            	                break;
	            	            case 2:
	            	                System.out.print("Enter new Phone No :");
	            	                newValue = sc.nextLine();
	            	                break;
	            	            case 3:
	            	                System.out.print("Enter new Email ID :");
	            	                newValue = sc.nextLine();
	            	                break;
	            	            default:
	            	                System.out.println("Invalid choice!");
	            	                break;
	            	        }

	            	        
	            	        if (ch >= 1 && ch <= 3) {
	            	            boolean update = cdao.updateSpecificField(uid, ch, newValue);

	            	            if (update)
	            	                System.out.println("Customer field updated successfully!");
	            	            else
	            	                System.out.println("Update failed or no matching record found.");
	            	        }
	            	    } catch (SQLException e) {
	            	        System.out.println("Database error: " + e);
	            	    }
	            	    break;

	            	case 5:
	            		System.out.print("Enter ID to Delete :");
						int did = sc.nextInt();
						boolean deleted = cdao.removeCustomer(did); 
						
						if (deleted)
					        System.out.println("Customer deleted successfully!");
					    else
					        System.out.println("Customer ID not found!");  
						break;
	            		
	            	case 0:
	            		return;
	            }
		}
	}
	
	// ---------------- VEHICLE MENU ----------------
    private static void vehicleMenu(Scanner sc, VehicleDAO vdao) throws SQLException{
        while (true) {
            System.out.println("\n--- VEHICLE MENU ---");
            System.out.println("1. Add Vehicle");
            System.out.println("2. View Vehicles");
            System.out.println("3. Update Vehicle");
            System.out.println("4. Delete Vehicle");
            System.out.println("0. Back to Main Menu");
            System.out.print("Enter your choice: ");

            int choice = sc.nextInt();
            sc.nextLine();
            
            switch (choice) {
                case 1:
					System.out.print("Enter Customer ID :");
					int cID = sc.nextInt();
					sc.nextLine();
					System.out.print("Enter Vehicle Number :");
					String vehicleNum = sc.nextLine();
					
					System.out.print("Enter Vehicle Model :");
					String vModel = sc.nextLine();
					System.out.print("Enter Vehicle Type :");
					String vType = sc.nextLine();
					
					Vehicle v = new Vehicle(0, cID, vehicleNum, vModel, vType);
	                boolean added = vdao.addVehicle(v);

	                if (added)
	                    System.out.println("Vehicle added successfully!");
	                else
	                    System.out.println("Failed to add Vehicle!");
                    break;
                    
                case 2:
                	ArrayList<Vehicle> allVehicle = vdao.viewVehicles();
					
					for(Vehicle k : allVehicle)
					{
						System.out.println(k.getvID() + " " +  k.getcID() + "  " + k.getVehicleNum() + "  " + k.getvModel() + "  " + k.getvType());
					}
					break;
                    
                case 3:
                	System.out.print("Enter Vehicle ID :");
                    int vID = sc.nextInt();
                    sc.nextLine();
                    System.out.print("Enter Vehicle Model :");
                    String model = sc.nextLine();
                    System.out.print("Enter Vehicle Type :");
                    String type = sc.nextLine();
                    
                    Vehicle u = new Vehicle(vID, 0, " ", model, type);
                    boolean updated = vdao.editVehicle(u);
                    
                    if (updated)
                        System.out.println("Vehicle updated successfully!");
                    else
                        System.out.println("Failed to update Vehicle!");
                    break;
                    
                case 4:
                	System.out.print("Enter Vehicle ID to Delete :");
					int did = sc.nextInt();
					boolean deleted = vdao.removeVehicle(did);
					
					if (deleted)
				        System.out.println("Vehicle deleted successfully!");
				    else
				        System.out.println("Vehicle ID not found!");  
                    break;
                    
                case 0:
                    return;
                    
                default:
                    System.out.println("Invalid choice!");
            }
        }
    }

    // ---------------- SERVICE MENU ----------------
    private static void serviceMenu(Scanner sc, ServiceDAO sdao) throws SQLException{
        while (true) {
            System.out.println("\n--- SERVICE MENU ---");
            System.out.println("1. Add Service");
            System.out.println("2. View Services");
            System.out.println("3. Update Service");
            System.out.println("4. Delete Service");
            System.out.println("0. Back to Main Menu");
            System.out.print("Enter your choice: ");

            int choice = sc.nextInt();
            sc.nextLine();
            
            switch (choice) {
                case 1:
                	System.out.print("Enter Vehicle ID :");
					int vID = sc.nextInt();
					sc.nextLine();
					System.out.print("Enter Service Type :");
					String sType = sc.nextLine();
					System.out.print("Enter Service Date :");
					String sDate = sc.nextLine();
					System.out.print("Enter Service Status :");
					String sStatus = sc.nextLine();
					System.out.print("Enter Service Cost :");
					int sCost = sc.nextInt();
					sc.nextLine();
					
					Service s = new Service(0, vID, sType, sDate, sStatus, sCost);
	                boolean added = sdao.addService(s); 

	                if (added)
	                    System.out.println("Service added successfully!");
	                else
	                    System.out.println("Failed to add Service!");
                    break;
                    
                case 2:
                	ArrayList<Service> allService = sdao.viewServices();
					
					for(Service k : allService)
					{
						System.out.println(k.getsID() + " " +k.getvID() + " " +  k.getsType() + "  " + k.getsDate() + "  " + k.getsStatus() + "  " + k.getsCost());
					}
                    break;
                    
                case 3:
                	System.out.print("Enter Service ID :");
                    int sID = sc.nextInt();
                    sc.nextLine();
                    System.out.print("Enter Service Date :");
                    String sDate2 = sc.next();
                    System.out.print("Enter Service Status :");
                    String sStatus2 = sc.next();
                    
                    Service u = new Service(sID,sDate2, sStatus2); 
                    boolean edit = sdao.editService(u);
                    
                    if (edit)
                        System.out.println("Service updated successfully!");
                    else
                        System.out.println("Failed to update Service!");
                    break;
                    
                case 4:
                	System.out.print("Enter Service ID to Delete:");
					int did = sc.nextInt();
					boolean deleted = sdao.removeService(did);
					
					if (deleted)
				        System.out.println("Service deleted successfully!");
				    else
				        System.out.println("Service ID not found!");  
                    break;
                    
                case 0:
                    return;
                    
                default:
                    System.out.println("Invalid choice!");
            }
        }
    }
}
